[package]
name = "ehentai-dl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
fern_colored = { version = "0.6.1", features = ["colored"] }
log = "0.4.17"
regex = "1.7.1"
reqwest = {version = "0.11.14", features = ["blocking"]}
tempfile = "3.3.0"
urlencoding = "2.1.2"